### ISSUE TITLE
Issue with 3.4.8

### ISSUE THREAD

**Issue by RocketRider** [juliopontes/staticcontent#10]
I tried your plugin with Joomla 3.4.8, but it does not export anything.

It created the folder, and says it was successful but no files get created...

**Comment by juliopontes** [comment]
will check asap.

**Comment by thednp** [comment]
I believe your destination folder isn't writable.

**Comment by twoduschegg** [comment]
Hi, i have the same Problem... Export-directory has 0755
any further ideas? I'm sick of website-hacks
many thanks

**Comment by juliopontes** [comment]
Sorry for delay,

Did you try to export only 1 page?

**Comment by twoduschegg** [comment]
Hi thanks for the reply, 
yes 1 page, a few pages and the whole site

**Comment by phajek** [comment]
I have the same problem on 3.4.8.

**Comment by juliopontes** [comment]
in development.
