### ISSUE TITLE
Does not work on 3.5, invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by kbotnen** [juliopontes/staticcontent#12]
Hi,

I get the following error message on a newly upgraded 3.5 site that I try to export:

<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/home/username/public_html/components/com_staticcontent/helpers/document.php</b> on line <b>239</b><br />
COM_STATICCONTENT_MSG_SUCCESS_CREATED_SITE
- K -

**Comment by juliopontes** [comment]
will be fixed in next version. soon
