### ISSUE TITLE
Does not work on Joomla 3.6.4: syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) 

### ISSUE THREAD

**Issue by cederom** [juliopontes/staticcontent#18]
<br />
<b>Parse error</b>:  syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in <b>/home/.../joomla/components/com_staticcontent/helpers/menu.php</b> on line <b>96</b><br />

**Comment by juliopontes** [comment]
I'm building a new version.

**Comment by cederom** [comment]
Thank you! Awsome project! Very good solution for sites under constant attack =)

**Comment by hawkinsjon** [comment]
HI @juliopontes, curious if the new version was ever made? We're very excited for this component. Thanks!

**Comment by juliopontes** [comment]
I'm starting a new version this month. Update asap.
