### ISSUE TITLE
Parse error Joomla 2.5.28

### ISSUE THREAD

**Issue by MichelleDiamond** [juliopontes/staticcontent#20]
<br />
<b>Parse error</b>:  syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in <b>/home/mediator/public_html/components/com_staticcontent/helpers/menu.php</b> on line <b>96</b><br />

**Comment by juliopontes** [comment]
Fixed in new version, soon.

**Comment by MichelleDiamond** [comment]
Thank you
