### ISSUE TITLE
Not working on Joomla 3.3.6

### ISSUE THREAD

**Issue by MartinMikita** [juliopontes/staticcontent#5]
Button 'Custom export' reports this error:

```
Fatal error: Call to undefined method JModel::getInstance() in
 /administrator/components/com_staticcontent/views/menus/view.html.php on line 11
```

And generating files is not working - request URLs are without slash (ie it requests `/en-ushometarget` instead of `/en-us/home/target`) so every page except home page is empty

**Comment by juliopontes** [comment]
Thanks for report will try to update asap.

**Comment by WooDzu** [comment]
Just hit the same issue on virgin Joomla 3.4.1
The component has managed to create a index.php.html file but it contains rss feed instead of home page.

**Comment by PixelZombie** [comment]
I'm interested in this extension too! I'm on 3.3.4 and it created the output folder and an empty index.html-file. It would be awesome seeing it working :-)

**Comment by nutthawan** [comment]
I got the blank index.phpth.html file once I clicked "Create files", it would be a great extension if it works.
By the way, thanks a lot for your contributions

**Comment by WooDzu** [comment]
Hi @juliopontes 
PR sent. Now we're talking
